apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: crypto-org
      defaultBucket: crypto-metrics
      tlsSkipVerify: true
    secureJsonData:
      token: admin-token-secret-12345
    editable: true

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
